//Mapping Way
var data = {
	subjectPropertyAddress: '',//Normal TextArea or input type="text" or date example -- subjectPropertyAddress: '123 Address'
	subjectStateSelected: ['Select'],//Normal dropdown example -- subjectStateSelected: ['CT']
	subjectCity: '',
	subjectZip: '',
	subjectCounty: '',
	subjectBorrower: '',
	subjectOwnerOfPublicRecord: '',
	subjectLegalDescription: '',
	subjectAssessorsParcel: '',
	subjectTaxYearSelected: ['Select'],
	subjectReTaxes: '',
	subjectNeighborhoodName: '',
	subjectMapReference: '',
	subjectCensusTract: '',
	subjectOccupantSelected: ['Select'],
	subjectSpecialAssessments: '',
	subjectPudHoa: '',
	subjectPudHoaFrequencySelected: ['Select'],
	subjectPropertyRightsAppraisedSelected: ['Select'],
	subjectPropertyRightsAppraisedOther: '',
	subjectAssignmentTypeSelected: ['Select'],
	subjectAssignmentTypeOther: '',
	subjectLenderClient: '',
	subjectAddress: '',
	subjectCurrentlyOfferedSelected: ['Select'],
	subjectDataSourceOfferedPrice: '',
	subjectUnitNum: '',
	subjectContractPrice: '',
	subjectDateOfContract: '',
	subjectPropertyRightsAppraised: ['Select'],
	subjectPropertyRightsAppraisedOther: '',
	subjectOriginalAppraisedValue: '',
	subjectOriginalAppraiser: '',
	subjectCompanyName: '',
	subjectOriginalLenderClient: '',
	subjectAddress: '',
	subjectProjectName: '',
	subjectPhaseNumber: '',
	subjectHoa: '',
	subjectHoaFrequencySelected: '',
	
	contractAnalyzeContractChecked: '',
	contractAnalyzeExplain: '',
	contractPrice: '',
	contractDate: '',//Date example -- contractDate: '2013-11-21'
	contractPropertySellerChecked: '',
	contractDataSources: '',
	contractFinancialAssistanceChecked: '',
	contractFinancialAssistanceYes: '',
	contractManufacturerChecked: '',
	contractManufacturerExplain: '',
	contractRetailerName: '',
	
	neighborhoodLocationSelected: '',
	neighborhoodBuiltUpSelected: '',
	neighborhoodGrowthSelected: '',
	neighborhoodPropertyValuesSelected: '',
	neighborhoodDemandSupplySelected: '',
	neighborhoodMarketingSelected: '',
	neighborhoodPrice: '',
	neighborhoodAge: '',
	neighborhoodPriceSelected: '',
	neighborhoodOneUnit: '',
	neighborhoodTwoToFour: '',
	neighborhoodMultiFamily: '',
	neighborhoodCommercial: '',
	neighborhoodOther: '',
	neighborhoodDescription: '',
	neighborhoodConditions: '',
	neighborhoodBoundaries: '',
	
	siteDimensions: '',
	siteArea: '',
	siteShape: '',
	siteView: '',
	siteZoning: '',
	siteZoningDescription: '',
	siteZoningComplianceSelected: '',
	siteZoningComplianceOther: '',
	sitePropertyImprovedSelected: '',
	sitePropertyImprovedOther: '',
	siteElectricitySelected: '',
	siteGasSelected: '',
	siteWaterSelected: '',
	siteSanitarySewerSelected: '',
	siteStreetSelected: '',
	siteAlleySelected: '',
	siteFloodHazardSelected: '',
	siteFemaFloodZone: '',
	siteFemaMap: '',
	siteFemaMapDate: '',
	siteTypicalSelected: '',
	siteTypicalSelectedNo: '',
	siteAdverseSelected: '',
	siteAdverseSelectedOther: '',
	siteAdequateVehicularAccessSelected: '',
	siteAdequateVehicularAccessNo: '',
	siteStreetMaintainedSelected: '',
	siteStreetMaintainedNo: '',
	
	siteTopography: '',
	siteSize: '',
	siteDensity: '',
	siteZoningRegulationsSelected: '',
	siteElectricityOther: '',
	siteGasOther: '',
	siteWaterOther: '',
	siteSanitarySewerOther: '',
	siteZoningCurrentDensity: '',

	improvementsUnitsSelected: ['Select'],
	improvementsNumOfStories: '',
	improvementsTypeSelected: ['Select'],
	improvementsDesignStyle: '',
	improvementsYearBuilt: '',
	improvementsEffectiveAgeYears: '',
	improvementsFoundationChecked: '',//Radio Button Example -- improvementsFoundationChecked: 'Something' (In the radio group, "Something" is selected)
	improvementsBasementArea: '',
	improvementsBasementFinish: '',
	improvementsSumpPumpChecked: [],//Checkbox Example -- improvementsSumpPumpChecked: ['Something1','Something3'] (In the checkbox group, 1 and 3 are selected)
	improvementsEvidenceOfSelected: ['Select'],
	improvementsFoundationWalls: '',
	improvementsExteriorWalls: '',
	improvementsRoofSurface: '',
	improvementsGuttersAndDownspouts: '',
	improvementsWindowType: '',
	improvementsStormSash: '',
	improvementsScreens: '',
	improvementsFloors: '',
	improvementsWalls: '',
	improvementsTrimFinish: '',
	improvementsBathFloor: '',
	improvementsBathWainscot: '',
	improvementsAtticSelected: ['Select'],
	improvementsHeatingSelected: ['Select'],
	improvementsFuel: '',
	improvementsCoolingSelected: ['Select'],
	improvementsAmenitiesSelected: ['Select'],
	improvementsCarStorageSelected: ['Select'],
	improvementsNumCars: '',
	improvementsDrivewaySurfaceSelected: ['Select'],
	improvementsAppliancesChecked:[],
	improvementsAppliancesOther: '',
	improvementsRooms: '',
	improvementsBedrooms: '',
	improvementsBaths: '',
	improvementsSqFtGrossLivingArea: '',
	improvementsAdditionalFeatures: '',
	improvementsPropertyCondition: '',
	improvementsPhysicalDeficienciesSelected: ['Select'],
	improvementsPhysicalDeficienciesOther: '',
	improvementsConformToNeighborhoodSelected: ['Select'],
	improvementsConformToNeighborhoodOther: '',
	improvementsUnits1004cSelected: ['Select'],
	improvementsNumOfSections: '',
	improvementsSkirting: '',
	improvementsDoors: '',
	improvementsAdditionalModifications: '',
	improvementsInstallersName: '',
	improvementsDateInstalled: '',
	improvementsModelYear: '',
	improvementsPermanentFoundationSelected: ['Select'],
	improvementsPermanentFoundationNo: '',
	improvementsHitchRemovedSelected: ['Select'],
	improvementsHitchRemovedNo: '',
	improvementsPermanentSewageSelected: ['Select'],
	improvementsPermanentSewageNo: '',
	improvementsSufficientDwellingSelected: ['Select'],
	improvementsSufficientDwellingNo: '',
	improvementsMhQualitySelected: ['Select'],
	improvementsMhQualitySource: '',
	improvements1025UnitsSelected: ['Select'],
	improvementsNumOfBuildings: '',
	improvementsRefrigeratorNum: '',
	improvementsRangeNum: '',
	improvementsDishwasherNum: '',
	improvementsDisposalNum: '',
	improvementsMicrowaveNum: '',
	improvementsWasherDryerNum: '',
	improvementsOtherNum: '',
	improvementsUnitOneRooms: '',
	improvementsUnitOneBedrooms: '',
	improvementsUnitOneBaths: '',
	improvementsUnitOneGrossLivingArea: '',
	improvementsUnitTwoRooms: '',
	improvementsUnitTwoBedrooms: '',
	improvementsUnitTwoBaths: '',
	improvementsUnitTwoGrossLivingArea: '',
	improvementsUnitThreeRooms: '',
	improvementsUnitThreeBedrooms: '',
	improvementsUnitThreeBaths: '',
	improvementsUnitThreeGrossLivingArea: '',
	improvementsUnitFourRooms: '',
	improvementsUnitFourBedrooms: '',
	improvementsUnitFourBaths: '',
	improvementsUnitFourGrossLivingArea: '',
	improvementsSubjectToRentControlSelected: ['Select'],
	improvementsSubjectToRentControlYes: '',
	improvementsSourcesForPhysicalCharChecked: '',
	improvementsSourcesForPhysicalCharOther: '',
	improvementsDatSourcesGrossLivingArea: '',
	
	scaComparableCount: '',
	scaComparableFromPrice: '',
	scaComparableToPrice: '',
	scaComparableSaleCount: '',
	scaComparableSaleFromPrice: '',
	scaComparableSaleToPrice: '',
	//Subject
	scaSubjectAddress: '',
	scaSubjectSalePrice: '',
	scaSubjectGrossPrice: '',
	scaSubjectLocation: '',
	scaSubjectLeasehold: '',
	scaSubjectSite: '',
	scaSubjectView: '',
	scaSubjectDesignStyle: '',
	scaSubjectQualityOfConstruction: '',
	scaSubjectActualAge: '',
	scaSubjectCondition: '',
	scaSubjectTotalRooms: '',
	scaSubjectBedrooms: '',
	scaSubjectBaths: '',
	scaSubjectGrossLivingArea: '',
	scaSubjectRoomsBelowGrade: '',
	scaSubjectFunctionalUtility: '',
	scaSubjectHeatingCooling: '',
	scaSubjectEnergyEfficientItems: '',
	scaSubjectGarageCarport: '',
	scaSubjectGarageCarport: '',
	scaSubjectPorch: '',
	scaSubjectGrossMonthlyRent: '',
	scaSubjectGrossRentMultiplier: '',
	scaSubjectPricePerUnit: '',
	scaSubjectPricePerRoom: '', 
	scaSubjectPricePerBedroom: '',
	scaRentControlChecked: '',
	scaSubjectGrossBuildingArea: '',
	scaSubjectUnitOneTotalRooms: '',
	scaSubjectUnitOneTotalBedrooms: '',
	scaSubjectUnitOneTotalBaths: '',
	scaSubjectUnitTwoTotalRooms: '',
	scaSubjectUnitTwoTotalBedrooms: '',
	scaSubjectUnitTwoTotalBaths: '',
	scaSubjectUnitThreeTotalRooms: '',
	scaSubjectUnitThreeTotalBedrooms: '',
	scaSubjectUnitThreeTotalBaths: '',
	scaSubjectUnitFourTotalRooms: '',
	scaSubjectUnitFourTotalBedrooms: '',
	scaSubjectUnitFourTotalBaths: '',
	scaSubjectBasementDescription: '',
	scaSubjectBasementFinishedRooms: '',
	scaSubjectParkingOnOff: '',
	//Comparable 1
	scaCompOneAddress: '',
	scaCompOneProximity: '',
	scaCompOneSalePrice: '',
	scaCompOneGrossPrice: '',
	scaCompOneDataSources: '',
	scaCompOneVerificationSources: '',
	scaCompOneConcessions: '',
	scaCompOneConcessionsAdjustment: '',
	scaCompOneDateOfSale: '',
	scaCompOneDateOfSaleAdjustment: '',
	scaCompOneLocation: '',
	scaCompOneLocationAdjustment: '',
	scaCompOneLeasehold: '',
	scaCompOneLeaseholdAdjustment: '',
	scaCompOneSite: '',
	scaCompOneSiteAdjustment: '',
	scaCompOneView: '',
	scaCompOneViewAdjustment: '',
	scaCompOneDesignStyle: '',
	scaCompOneDesignStyleAdjustment: '',
	scaCompOneQuality: '',
	scaCompOneQualityAdjustment: '',
	scaCompOneActualAge: '',
	scaCompOneActualAgeAdjustment: '',
	scaCompOneCondition: '',
	scaCompOneConditionAdjustment: '',
	scaCompOneTotalRooms: '',
	scaCompOneBedrooms: '',
	scaCompOneBaths: '',
	scaCompOneGrossLivingArea: '',
	scaCompOneGrossLivingAreaAdjustment: '',
	scaCompOneRoomsBelowGrade: '',
	scaCompOneRoomsBelowGradeAdjustment: '',
	scaCompOneFunctionalUtility: '',
	scaCompOneFunctionalUtilityAdjustment: '',
	scaCompOneHeatingCooling: '',
	scaCompOneHeatingCoolingAdjustment: '',
	scaCompOneEnergyItems: '',
	scaCompOneEnergyItemsAdjustment: '',
	scaCompOneGarage: '',
	scaCompOneGarageAdjustment: '',
	scaCompOnePorch: '',
	scaCompOnePorchAdjustment: '',
	scaCompOneNetAdjustmentChecked: '',
	scaCompOneNetAdjustment: '',
	scaCompOneNetAdjustmentPercent: '',
	scaCompOneGrossAdjustmentPercent: '',
	scaCompOneDollarAdjustment: '',
	scaCompOneGrossPriceBldg: '',
	scaCompOneGrossMonthlyRent: '',
	scaCompOneGrossRentMultiplier: '',
	scaCompOnePricePerUnit: '',
	scaCompOnePricePerRoom: '',
	scaCompOnePricePerBedroom: '',
	scaCompOneRentControlChecked: '',
	scaCompOneGrossBuildingArea: '',
	scaCompOneGrossBuildingAreaAdjustment: '',
	scaCompOneUnitOneTotalRooms: '',
	scaCompOneUnitOneTotalBedrooms: '',
	scaCompOneUnitOneTotalBaths: '',
	scaCompOneUnitOneTotalRoomsAdjustment: '',
	scaCompOneUnitTwoTotalRooms: '',
	scaCompOneUnitTwoTotalBedrooms: '',
	scaCompOneUnitTwoTotalBaths: '',
	scaCompOneUnitTwoTotalRoomsAdjustment: '',
	scaCompOneUnitThreeTotalRooms: '',
	scaCompOneUnitThreeTotalBedrooms: '',
	scaCompOneUnitThreeTotalBaths: '',
	scaCompOneUnitThreeTotalRoomsAdjustment: '',
	scaCompOneUnitFourTotalRooms: '',
	scaCompOneUnitFourTotalBedrooms: '',
	scaCompOneUnitFourTotalBaths: '',
	scaCompOneUnitFourTotalRoomsAdjustment: '',
	scaCompOneBasementDescription: '',
	scaCompOneBasementDescriptionAdjustment: '',
	scaCompOneBasementFinsihedRooms: '',
	scaCompOneBasementFinishedRoomsAdjustment: '',
	scaCompOneParkingOnOff: '',
	scaCompOneParkingOnOffAdjustment: '',
	scaCompOneAdjustedPricePerUnit: '',
	scaCompOneAdjustedPricePerRoom: '',
	scaCompOneAdjustedPricePerBedroom: '',
	//Comparable 2
	scaCompTwoAddress: '',
	scaCompTwoProximity: '',
	scaCompTwoSalePrice: '',
	scaCompTwoGrossPrice: '',
	scaCompTwoDataSources: '',
	scaCompTwoVerificationSources: '',
	scaCompTwoConcessions: '',
	scaCompTwoConcessionsAdjustment: '',
	scaCompTwoDateOfSale: '',
	scaCompTwoDateOfSaleAdjustment: '',
	scaCompTwoLocation: '',
	scaCompTwoLocationAdjustment: '',
	scaCompTwoLeasehold: '',
	scaCompTwoLeaseholdAdjustment: '',
	scaCompTwoSite: '',
	scaCompTwoSiteAdjustment: '',
	scaCompTwoView: '',
	scaCompTwoViewAdjustment: '',
	scaCompTwoDesignStyle: '',
	scaCompTwoDesignStyleAdjustment: '',
	scaCompTwoQuality: '',
	scaCompTwoQualityAdjustment: '',
	scaCompTwoActualAge: '',
	scaCompTwoActualAgeAdjustment: '',
	scaCompTwoCondition: '',
	scaCompTwoConditionAdjustment: '',
	scaCompTwoTotalRooms: '',
	scaCompTwoBedrooms: '',
	scaCompTwoBaths: '',
	scaCompTwoGrossLivingArea: '',
	scaCompTwoGrossLivingAreaAdjustment: '',
	scaCompTwoRoomsBelowGrade: '',
	scaCompTwoRoomsBelowGradeAdjustment: '',
	scaCompTwoFunctionalUtility: '',
	scaCompTwoFunctionalUtilityAdjustment: '',
	scaCompTwoHeatingCooling: '',
	scaCompTwoHeatingCoolingAdjustment: '',
	scaCompTwoEnergyItems: '',
	scaCompTwoEnergyItemsAdjustment: '',
	scaCompTwoGarage: '',
	scaCompTwoGarageAdjustment: '',
	scaCompTwoPorch: '',
	scaCompTwoPorchAdjustment: '',
	scaCompTwoNetAdjustmentChecked: '',
	scaCompTwoNetAdjustment: '',
	scaCompTwoNetAdjustmentPercent: '',
	scaCompTwoGrossAdjustmentPercent: '',
	scaCompTwoDollarAdjustment: '',//
	scaCompTwoGrossPriceBldg: '',
	scaCompTwoGrossMonthlyRent: '',
	scaCompTwoGrossRentMultiplier: '',
	scaCompTwoPricePerUnit: '',
	scaCompTwoPricePerRoom: '',
	scaCompTwoPricePerBedroom: '',
	scaCompTwoRentControlChecked: '',
	scaCompTwoGrossBuildingArea: '',
	scaCompTwoGrossBuildingAreaAdjustment: '',
	scaCompTwoUnitOneTotalRooms: '',
	scaCompTwoUnitOneTotalBedrooms: '',
	scaCompTwoUnitOneTotalBaths: '',
	scaCompTwoUnitOneTotalRoomsAdjustment: '',
	scaCompTwoUnitTwoTotalRooms: '',
	scaCompTwoUnitTwoTotalBedrooms: '',
	scaCompTwoUnitTwoTotalBaths: '',
	scaCompTwoUnitTwoTotalRoomsAdjustment: '',
	scaCompTwoUnitThreeTotalRooms: '',
	scaCompTwoUnitThreeTotalBedrooms: '',
	scaCompTwoUnitThreeTotalBaths: '',
	scaCompTwoUnitThreeTotalRoomsAdjustment: '',
	scaCompTwoUnitFourTotalRooms: '',
	scaCompTwoUnitFourTotalBedrooms: '',
	scaCompTwoUnitFourTotalBaths: '',
	scaCompTwoUnitFourTotalRoomsAdjustment: '',
	scaCompTwoBasementDescription: '',
	scaCompTwoBasementDescriptionAdjustment: '',
	scaCompTwoBasementFinsihedRooms: '',
	scaCompTwoBasementFinishedRoomsAdjustment: '',
	scaCompTwoParkingOnOff: '',
	scaCompTwoParkingOnOffAdjustment: '',
	scaCompTwoAdjustedPricePerUnit: '',
	scaCompTwoAdjustedPricePerRoom: '',
	scaCompTwoAdjustedPricePerBedroom: '',
	//Comparable 3
	scaCompThreeAddress: '',
	scaCompThreeProximity: '',
	scaCompThreeSalePrice: '',
	scaCompThreeGrossPrice: '',
	scaCompThreeDataSources: '',
	scaCompThreeVerificationSources: '',
	scaCompThreeConcessions: '',
	scaCompThreeConcessionsAdjustment: '',
	scaCompThreeDateOfSale: '',
	scaCompThreeDateOfSaleAdjustment: '',
	scaCompThreeLocation: '',
	scaCompThreeLocationAdjustment: '',
	scaCompThreeLeasehold: '',
	scaCompThreeLeaseholdAdjustment: '',
	scaCompThreeSite: '',
	scaCompThreeSiteAdjustment: '',
	scaCompThreeView: '',
	scaCompThreeViewAdjustment: '',
	scaCompThreeDesignStyle: '',
	scaCompThreeDesignStyleAdjustment: '',
	scaCompThreeQuality: '',
	scaCompThreeQualityAdjustment: '',
	scaCompThreeActualAge: '',
	scaCompThreeActualAgeAdjustment: '',
	scaCompThreeCondition: '',
	scaCompThreeConditionAdjustment: '',
	scaCompThreeTotalRooms: '',
	scaCompThreeBedrooms: '',
	scaCompThreeBaths: '',
	scaCompThreeGrossLivingArea: '',
	scaCompThreeGrossLivingAreaAdjustment: '',
	scaCompThreeRoomsBelowGrade: '',
	scaCompThreeRoomsBelowGradeAdjustment: '',
	scaCompThreeFunctionalUtility: '',
	scaCompThreeFunctionalUtilityAdjustment: '',
	scaCompThreeHeatingCooling: '',
	scaCompThreeHeatingCoolingAdjustment: '',
	scaCompThreeEnergyItems: '',
	scaCompThreeEnergyItemsAdjustment: '',
	scaCompThreeGarage: '',
	scaCompThreeGarageAdjustment: '',
	scaCompThreePorch: '',
	scaCompThreePorchAdjustment: '',
	scaCompThreeNetAdjustmentChecked: '',
	scaCompThreeNetAdjustment: '',
	scaCompThreeNetAdjustmentPercent: '',
	scaCompThreeGrossAdjustmentPercent: '',
	scaCompThreeDollarAdjustment: '',
	scaCompThreeGrossPriceBldg: '',
	scaCompThreeGrossMonthlyRent: '',
	scaCompThreeGrossRentMultiplier: '',
	scaCompThreePricePerUnit: '',
	scaCompThreePricePerRoom: '',
	scaCompThreePricePerBedroom: '',
	scaCompThreeRentControlChecked: '',
	scaCompThreeGrossBuildingArea: '',
	scaCompThreeGrossBuildingAreaAdjustment: '',
	scaCompThreeUnitOneTotalRooms: '',
	scaCompThreeUnitOneTotalBedrooms: '',
	scaCompThreeUnitOneTotalBaths: '',
	scaCompThreeUnitOneTotalRoomsAdjustment: '',
	scaCompThreeUnitTwoTotalRooms: '',
	scaCompThreeUnitTwoTotalBedrooms: '',
	scaCompThreeUnitTwoTotalBaths: '',
	scaCompThreeUnitTwoTotalRoomsAdjustment: '',
	scaCompThreeUnitThreeTotalRooms: '',
	scaCompThreeUnitThreeTotalBedrooms: '',
	scaCompThreeUnitThreeTotalBaths: '',
	scaCompThreeUnitThreeTotalRoomsAdjustment: '',
	scaCompThreeUnitFourTotalRooms: '',
	scaCompThreeUnitFourTotalBedrooms: '',
	scaCompThreeUnitFourTotalBaths: '',
	scaCompThreeUnitFourTotalRoomsAdjustment: '',
	scaCompThreeBasementDescription: '',
	scaCompThreeBasementDescriptionAdjustment: '',
	scaCompThreeBasementFinsihedRooms: '',
	scaCompThreeBasementFinishedRoomsAdjustment: '',
	scaCompThreeParkingOnOff: '',
	scaCompThreeParkingOnOffAdjustment: '',
	scaCompThreeAdjustedPricePerUnit: '',
	scaCompThreeAdjustedPricePerRoom: '',
	scaCompThreeAdjustedPricePerBedroom: '',
	//Research and Data
	scaRndResearchDataChecked: '',
	scaRndResearchDataNot: '',
	scaRndMyResearchChecked: '',
	scaRndMyResearchDataSources: '',
	scaRndMyResearchComparableChecked: '',
	scaRndMyResearchComparableDataSources: '',
	scaRndSubjectDateOfPriorSale: '',
	scaRndCompOneDateOfPriorSale: '',
	scaRndCompTwoDateOfPriorSale: '',
	scaRndCompThreeDateOfPriorSale: '',
	scaRndSubjectPriceOfPriorSale: '',
	scaRndCompOnePriceOfPriorSale: '',
	scaRndCompTwoPriceOfPriorSale: '',
	scaRndCompThreePriceOfPriorSale: '',
	scaRndSubjectDataSources: '',
	scaRndCompOneDataSources: '',
	scaRndCompTwoDataSources: '',
	scaRndCompThreeDataSources: '',
	scaRndSubjectEffectiveDate: '',
	scaRndCompOneEffectiveDate: '',
	scaRndCompTwoEffectiveDate: '',
	scaRndCompThreeEffectiveDate: '',
	scaRndSubjectComparableAnalysis: '',
	scaRndSubjectComparableSummary: '',
	//Summary
	scaValuePerUnitCost: '',
	scaValuePerUnitUnits: '',
	scaValuePerUnitTotal: '',
	scaValuePerRoomCost: '',
	scaValuePerRoomRooms: '',
	scaValuePerRoomTotal: '',
	scaValuePerGbaCost: '',
	scaValuePerGbaGba: '',
	scaValuePerGbaTotal: '',
	scaValuePerBedroomCost: '',
	scaValuePerBedroomBedrooms: '',
	scaValuePerBedroomTotal: '',
	scaSummaryIncludingRec: '',
	scaIndicatedValueBySca: '',
	
	scaSubjectAddressUnitNumber: '',
	scaSubjectProjectNamePhase: '',
	scaSubjectHoaAssessment: '',
	scaSubjectElementsFacilities: '',
	scaSubjectFloorLocation: '',
	scaCompOneAddressUnitNumber: '',
	scaCompOneProjectNamePhase: '',
	scaCompOneHoaAssessment: '',
	scaCompOneHoaAssessmentAdjustment: '',
	scaCompOneElementsFacilities: '',
	scaCompOneElementsFacilitiesAdjustment: '',
	scaCompOneFloorLocation: '',
	scaCompOneFloorLocationAdjustment: '',
	scaCompTwoAddressUnitNumber: '',
	scaCompTwoProjectNamePhase: '',
	scaCompTwoHoaAssessment: '',
	scaCompTwoHoaAssessmentAdjustment: '',
	scaCompTwoElementsFacilities: '',
	scaCompTwoElementsFacilitiesAdjustment: '',
	scaCompTwoFloorLocation: '',
	scaCompTwoFloorLocationAdjustment: '',
	scaCompThreeAddressUnitNumber: '',
	scaCompThreeProjectNamePhase: '',
	scaCompThreeHoaAssessment: '',
	scaCompThreeHoaAssessmentAdjustment: '',
	scaCompThreeElementsFacilities: '',
	scaCompThreeElementsFacilitiesAdjustment: '',
	scaCompThreeFloorLocation: '',
	scaCompThreeFloorLocationAdjustment: '',
	scaRndIndicatedValue: '',
	scaRndCompAnalysis: '',
	
	reconSalesCompApproach: '',
	reconCostApproach: '',
	reconIncomeApproach: '',
	reconApprasialStatusChecked: '',
	reconMarketValue: '',
	reconDateOfInspection: '',
	
	caSupportText: '',
	caEstimatedChecked: '',
	caSourceOfDataCost: '',
	caQualityRating: '',
	caEffectiveDate: '',
	caCommentsOnApproach: '',
	caEstimatedEconomicLife: '',
	caOpinionOfSiteValue: '',
	caDwellingOneSqFt: '',
	caDwellingOneCostPerSqFt: '',
	caDwellingOneTotalCost: '',
	caDwellingTwoSqFt: '',
	caDwellingTwoCostPerSqFt: '',
	caDwellingTwoTotalCost: '',
	caGarageSqFt: '',
	caGarageCostPerSqFt: '',
	caGarageTotalCost: '',
	caTotalEstimatedCostNew: '',
	caDepPhysical: '',
	caDepFunctional: '',
	caDepExternal: '',
	caDepTotal: '',
	caDepCostOfImprovements: '',
	caAsIsValue: '',
	caIndicatedValueByCa: '',
	caSectionOneArea: '',
	caSectionOnePricePer: '',
	caSectionOneTotal: '',
	caSectionTwoArea: '',
	caSectionTwoPricePer: '',
	caSectionTwoTotal: '',
	caSectionThreeArea: '',
	caSectionThreePricePer: '',
	caSectionThreeTotal: '',
	caSectionFourArea: '',
	caSectionFourPricePer: '',
	caSectionFourTotal: '',
	caSubtotal: '',
	caCostMultiplier: '',
	caModifiedSubtotal: '',
	caPhysDepModifier: '',
	caFunctionalObsolescence: '',
	caExternalDep: '',
	caDelivery: '',
	caOtherDep: '',
	caSubjectMarketValue: '',
	caIndicatedValue: '',
	caSectionOneLength: '',
	caSectionOneWidth: '',
	caSectionOneTotalArea: '',
	caSectionTwoLength: '',
	caSectionTwoWidth: '',
	caSectionTwoTotalArea: '',
	caSectionThreeLength: '',
	caSectionThreeWidth: '',
	caSectionThreeTotalArea: '',
	caSectionFourLength: '',
	caSectionFourWidth: '',
	caSectionFourTotalArea: '',
	caTotalGrossLivingArea: '',
	caNadaMonth: '',
	caNadaYear: '',
	caNadaMhState: '',
	caNadaRegion: '',
	caNadaLength: '',
	caNadaWidth: '',
	caGrayPg: '',
	caWhitePg: '',
	caBlackPg: '',
	caYellowPg: '',
	caFifteenYearsPg: '',
	caEstimatedRemainingEconomicLife: '',
	caOtherComments: '',
	caSummaryOfCa: '',
	
	incomeEstimatedMonthlyMarketRent: '',
	incomeGrossRentMultiplier: '',
	incomeIndicatedValueByIa: '',
	incomeSummaryOfIa: '',
	
	pudHomeownersAssSelected: ['Select'],
	pudUnitTypesSelected: ['Select'],
	pudLegalProjectName: '',
	pudTotalNumOfPhases: '',
	pudTotalNumOfUnits: '',
	pudTotalNumOfUnitsSold: '',
	pudTotalNumOfUnitsRented: '',
	pudTotalNumOfUnitsForSale: '',
	pudDataSources: '',
	pudConversionSelected: ['Select'],
	pudConversionDate: '',
	pudConversionDataSources: '',
	pudMultiDwellingSelected: ['Select'],
	pudMultiDwellingDataSources: '',
	pudFacilitiesCompleteSelected: ['Select'],
	pudFacilitiesCompleteNo: '',
	pudLeasedToHaSelected: ['Select'],
	pudLeasedToHaYes: '',
	pudDescribeCommon: '',
	
	//Appraiser
	appraiserSignature: 'data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==',//This is a data URL
	appraiserName: '',
	appraiserCompanyName: '',
	appraiserCompanyAddress: '',
	appraiserTelephoneNumber: '',
	appraiserEmail: '',
	appraiserDateOfSig: '',
	appraiserEffectiveDate: '',
	appraiserStateCertNum: '',
	appraiserStateLicNum: '',
	appraiserOther: '',
	appraiserStateNum: '',
	appraiserState: '',
	appraiserCertExpirationDate: '',
	appraiserAppraisedValue: '',
	appraiserPropertyAddress: '',
	//Lender/Client
	appraiserLcName: '',
	appraiserLcCompanyName: '',
	appraiserLcEmail: '',
	appraiserLcCompanyAddress: '',
	//SupervisoryAppraiser
	appraiserSaSignature: 'data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==',
	appraiserSaName: '',
	appraiserSaCompanyName: '',
	appraiserSaCompanyAddress: '',
	appraiserSaTelephoneNumber: '',
	appraiserSaEmail: '',
	appraiserSaSignatureDate: '',
	appraiserSaStateCertNum: '',
	appraiserSaStateLicNum: '',
	appraiserSaState: '',
	appraiserSaCertExpirationDate: '',
	appraiserSaSubjectPropertyChecked: '',
	appraiserSaSubjectPropertyDate: '',
	appraiserSaCompSalesChecked: '',
	appraiserSaCompSalesDate: '',
	signaturesDateOfInspection: '',
	
	hdpCertificateSelected: ['Select'],
	hdpCertificateDetails: '',
	hdpCertificateLabelSelected: ['Select'],
	hdpCertificateLabelNo: '',
	hdpVin: '',
	hdpCertificateLabelNum: '',
	hdpManufacturerName: '',
	hdpTradeModel: '',
	hdpDateOfManufacture: '',
	hdpMinHudRequirementsSelected: ['Select'],
	hdpMinHudRequirementsNo: '',
	
	saurMarketValueDeclinedChecked: '',
	saurMarketValueDeclinedDetails: '',
	
	cocAccordanceChecked: '',
	cocAccordanceNo: '',
	
	crdCurrentMonthlyRent: '',
	crdRentPerGrossBuildingArea: '',
	crdDataSources: '',
	crdDateOfLeases: '',
	crdSubjectUnitOneSize: '',
	crdSubjectUnitTwoSize: '',
	crdSubjectUnitThreeSize: '',
	crdSubjectUnitFourSize: '',
	crdSubjectUtilitiesIncluded: '',
	crdCompOneCurrentMonthlyRent: '',
	crdCompOneRentPerGrossBuildingArea: '',
	crdCompOneDateOfLeases: '',
	crdCompOneUnitOneSize: '',
	crdCompOneUnitTwoSize: '',
	crdCompOneUnitThreeSize: '',
	crdCompOneUnitFourSize: '',
	crdCompOneUtilitiesIncluded: '',
	crdCompTwoCurrentMonthlyRent: '',
	crdCompTwoRentPerGrossBuildingArea: '',
	crdCompTwoDateOfLeases: '',
	crdCompTwoUnitOneSize: '',
	crdCompTwoUnitTwoSize: '',
	crdCompTwoUnitThreeSize: '',
	crdCompTwoUnitFourSize: '',
	crdCompTwoUtilitiesIncluded: '',
	crdCompThreeCurrentMonthlyRent: '',
	crdCompThreeRentPerGrossBuildingArea: '',
	crdCompThreeDateOfLeases: '',
	crdCompThreeUnitOneSize: '',
	crdCompThreeUnitTwoSize: '',
	crdCompThreeUnitThreeSize: '',
	crdCompThreeUnitFourSize: '',
	crdCompThreeUtilitiesIncluded: '',
	crdRentalAnalysisData: '',
	
	srsUnitOneLeaseBeginDate: '',
	srsUnitOneLeaseEndDate: '',
	srsUnitTwoLeaseBeginDate: '',
	srsUnitTwoLeaseEndDate: '',
	srsUnitThreeLeaseBeginDate: '',
	srsUnitThreeLeaseEndDate: '',
	srsUnitFourLeaseBeginDate: '',
	srsUnitFourLeaseEndDate: '',
	srsCommentsOnLeaseDate: '',
	srsUnitOneRentUnfurnished: '',
	srsUnitOneRentFurnished: '',
	srsUnitOneTotalRent: '',
	srsUnitTwoRentUnfurnished: '',
	srsUnitTwoRentFurnished: '',
	srsUnitTwoTotalRent: '',
	srsUnitThreeRentUnfurnished: '',
	srsUnitThreeRentFurnished: '',
	srsUnitThreeTotalRent: '',
	srsUnitFourRentUnfurnished: '',
	srsUnitFourRentFurnished: '',
	srsUnitFourTotalRent: '',
	srsTotalActualMonthlyRent: '',
	srsOtherMonthlyIncome: '',
	srsTotalActualMonthlyIncome: '',
	srsUnitOneOpinionOfMarketRentUnfurnished: '',
	srsUnitOneOpinionOfMarketRentFurnished: '',
	srsUnitOneOpinionOfMarketRentTotalRent: '',
	srsUnitTwoOpinionOfMarketRentUnfurnished: '',
	srsUnitTwoOpinionOfMarketRentFurnished: '',
	srsUnitTwoOpinionOfMarketRentTotalRent: '',
	srsUnitThreeOpinionOfMarketRentUnfurnished: '',
	srsUnitThreeOpinionOfMarketRentFurnished: '',
	srsUnitThreeOpinionOfMarketRentTotalRent: '',
	srsUnitFourOpinionOfMarketRentUnfurnished: '',
	srsUnitFourOpinionOfMarketRentFurnished: '',
	srsUnitFourOpinionOfMarketRentTotalRent: '',
	srsTotalGrossMonthlyRent: '',
	srsOtherMonthlyIncomeItemize: '',
	srsTotalEstimatedMonthlyIncome: '',
	srsUtilitiesIncludedInMonthlyRentSelected: '',
	srsUtilitiesOther: '',
	srsOtherComments: '',
	
	pshResearchedChecked: '',
	pshResearchedExplain: '',
	pshResearchedHistoryChecked: '',
	pshResearchedHistoryDataSources: '',
	pshResearchedComparableHistoryChecked: '',
	pshResearchedComparableHistoryDataSources: '',
	pshSubjectDateOfPrior: '',
	pshSubjectPriceOfPrior: '',
	pshSubjectDataSources: '',
	pshSubjectEffectiveDateOfDataSources: '',
	pshCompOneDateOfPrior: '',
	pshCompOnePriceOfPrior: '',
	pshCompOneDataSources: '',
	pshCompOneEffectiveDateOfDataSources: '',
	pshCompTwoDateOfPrior: '',
	pshCompTwoPriceOfPrior: '',
	pshCompTwoDataSources: '',
	pshCompTwoEffectiveDateOfDataSources: '',
	pshCompThreeDateOfPrior: '',
	pshCompThreePriceOfPrior: '',
	pshCompThreeDataSources: '',
	pshCompThreeEffectiveDateOfDataSources: '',
	pshCompFourDateOfPrior: '',
	pshCompFourPriceOfPrior: '',
	pshCompFourDataSources: '',
	pshCompFourEffectiveDateOfDataSources: '',
	pshAnalysis: '',
	
	initialSubjectDateLeaseBegins: '',
	initialSubjectDateLeaseExpires: '',
	initialSubjectMonthlyRental: '',
	initialSubjectLessUtilites: '',
	initialSubjectAdjustedMonthlyRent: '',
	initialSubjectDataSources: '',
	initialSubjectConcessions: '',
	initialSubjectLocationView: '',
	initialSubjectDesignAppeal: '',
	initialSubjectAgeCondition: '',
	initialSubjectRoomCount: '',
	initialSubjectBedrooms: '',
	initialSubjectBaths: '',
	initialSubjectGrossLivingArea: '',
	initialSubjectOtherA: '',
	initialSubjectOtherB: '',
	initialCompOneDateLeaseBegins: '',
	initialCompOneDateLeaseExpires: '',
	initialCompOneMonthlyRental: '',
	initialCompOneLessUtilites: '',
	initialCompOneAdjustedMonthlyRent: '',
	initialCompOneDataSources: '',
	initialCompOneConcessions: '',
	initialCompOneConcessionsAdjustment: '',
	initialCompOneLocationView: '',
	initialCompOneLocationViewAdjustment: '',
	initialCompOneDesignAppeal: '',
	initialCompOneDesignAppealAdjustment: '',
	initialCompOneAgeCondition: '',
	initialCompOneAgeConditionAdjustment: '',
	initialCompOneRoomCount: '',
	initialCompOneBedrooms: '',
	initialCompOneBaths: '',
	initialCompOneGrossLivingArea: '',
	initialCompOneRoomsAdjustment: '',
	initialCompOneOtherA: '',
	initialCompOneOtherAAdjustment: '',
	initialCompOneOtherB: '',
	initialCompOneOtherBAdjustment: '',
	initialCompOneNetAdjustmentChecked: '',
	initialCompOneNetAdjustmentAmount: '',
	initialCompOneIndicatedMonthlyMarketRent: '',
	initialCompTwoDateLeaseBegins: '',
	initialCompTwoDateLeaseExpires: '',
	initialCompTwoMonthlyRental: '',
	initialCompTwoLessUtilites: '',
	initialCompTwoAdjustedMonthlyRent: '',
	initialCompTwoDataSources: '',
	initialCompTwoConcessions: '',
	initialCompTwoConcessionsAdjustment: '',
	initialCompTwoLocationView: '',
	initialCompTwoLocationViewAdjustment: '',
	initialCompTwoDesignAppeal: '',
	initialCompTwoDesignAppealAdjustment: '',
	initialCompTwoAgeCondition: '',
	initialCompTwoAgeConditionAdjustment: '',
	initialCompTwoRoomCount: '',
	initialCompTwoBedrooms: '',
	initialCompTwoBaths: '',
	initialCompTwoGrossLivingArea: '',
	initialCompTwoRoomsAdjustment: '',
	initialCompTwoOtherA: '',
	initialCompTwoOtherAAdjustment: '',
	initialCompTwoOtherB: '',
	initialCompTwoOtherBAdjustment: '',
	initialCompTwoNetAdjustmentChecked: '',
	initialCompTwoNetAdjustmentAmount: '',
	initialCompTwoIndicatedMonthlyMarketRent: '',
	initialCompThreeDateLeaseBegins: '',
	initialCompThreeDateLeaseExpires: '',
	initialCompThreeMonthlyRental: '',
	initialCompThreeLessUtilites: '',
	initialCompThreeAdjustedMonthlyRent: '',
	initialCompThreeDataSources: '',
	initialCompThreeConcessions: '',
	initialCompThreeConcessionsAdjustment: '',
	initialCompThreeLocationView: '',
	initialCompThreeLocationViewAdjustment: '',
	initialCompThreeDesignAppeal: '',
	initialCompThreeDesignAppealAdjustment: '',
	initialCompThreeAgeCondition: '',
	initialCompThreeAgeConditionAdjustment: '',
	initialCompThreeRoomCount: '',
	initialCompThreeBedrooms: '',
	initialCompThreeBaths: '',
	initialCompThreeGrossLivingArea: '',
	initialCompThreeRoomsAdjustment: '',
	initialCompThreeOtherA: '',
	initialCompThreeOtherAAdjustment: '',
	initialCompThreeOtherB: '',
	initialCompThreeOtherBAdjustment: '',
	initialCompThreeNetAdjustmentChecked: '',
	initialCompThreeNetAdjustmentAmount: '',
	initialCompThreeIndicatedMonthlyMarketRent: '',
	initialMarketDataComments: '',
	initialFinalReconciliation: '',
	initialEstimateDate: '',
	initialEstimateAmount: '',
	
	informationDataSource: '',
	informationDescriptionSelected: ['Select'],
	informationDescriptionOther: '',
	informationNumStories: '',
	informationNumElevators: '',
	informationTypeSelected: ['Select'],
	informationYearBuilt: '',
	informationAge: '',
	informationWalls: '',
	informationRoofSurface: '',
	informationTotalNum: '',
	informationRatio: '',
	informationType: '',
	informationGuestParking: '',
	informationNumUnits: '',
	informationUnitsCompleted: '',
	informationNumSale: '',
	informationNumSold: '',
	informationNumRented: '',
	informationNumOccupied: '',
	informationCompleteNumPhases: '',
	informationCompleteNumberUnit: '',
	informationCompleteNumberSale: '',
	informationCompleteNumberSold: '',
	informationCompleteNumberRented: '',
	informationCompleteNumberOccupied: '',
	informationIncompleteNumPhases: '',
	informationIncompleteNumUnits: '',
	informationIncompleteSale: '',
	informationIncompleteSold: '',
	informationIncompleteRented: '',
	informationIncompleteOccupied: '',
	informationOccupancyChecked: '',
	informationHoaDeveloperChecked: '',
	informationManagmentSelected: '',
	informationManagmentAgent: '',
	informationSingleEntitySelected: ['Select'],
	informationSingleEntityYes: '',
	informationCondominiumSelected: ['Select'],
	informationCondominiumYes: '',
	informationRecreationSelected: ['Select'],
	informationRecreationNo: '',
	informationSpaceSelected: ['Select'],
	informationSpaceYes: '',
	informationQuality: '',
	informationRecreational: '',
	informationCommonElementsSelected: ['Select'],
	informationCommonElementsYes: '',
	informationRentSelected: ['Select'],
	informationRentYes: '',
	informationSizeTypeSelected: ['Select'],
	informationSizeTypeNo: '',
	
	DescriptionUnitCharge: '',
	DescriptionPerMonth: '',
	DescriptionGrossArea: '',
	DescriptionUtilitesChecked: '',
	DescriptionUtilitiesOther: '',
	DescriptionSourcesChecked: '',
	DescriptionSourcesOther: '',
	DescriptionFloorNum: '',
	DescriptionNumLevels: '',
	DescriptionHeatType: '',
	DescriptionFuel: '',
	DescriptionAcTypeSelected: ['Select'],
	DescriptionAcTypeOther: '',
	DescriptionFloors: '',
	DescriptionWalls: '',
	DescriptionTrimFinish: '',
	DescriptionBathWainscot: '',
	DescriptionDoors: '',
	DescriptionAmenitiesChecked: ['Select'],
	DescriptionFireplaceNum: '',
	DescriptionWoodstoveNum: '',
	DescriptionAppliancesChecked: '',
	DescriptionCarStorageSelected: ['Select'],
	DescriptionNumCars: '',
	DescriptionAssignedChecked: '',
	DescriptionParkingSpot: '',
	DescriptionRooms: '',
	DescriptionBedrooms: '',
	DescriptionBaths: '',
	DescriptionLivingArea: '',
	DescriptionHeatingCoolingSelected: ['Select'],
	DescriptionHeatingCoolingOther: '',
	DescriptionFeatures: '',
	DescriptionCondition: '',
	DescriptionDeficienciesSelected: ['Select'],
	DescriptionDeficienciesYes: '',
	DescriptionConformSelected: ['Select'],
	DescriptionConformNo: '',
	
	AnalysisAnalyzeChecked: '',
	AnalysisBudgetExplain: '',
	AnalysisFeesSelected: ['Select'],
	AnalysisFeesYes: '',
	AnalysisUnitChargeSelected: ['Select'],
	AnalysisUnitChargeHighLow: '',
	AnalysisCharacteristicsSelected: ['Select'],
	AnalysisCharacteristicsYes: '',
	
	reconAppraisalDate: '',
	reconEffectiveDate: '',
	
	//Comments Timeline 
	notesComments: [],
	notesAddComment: function(a, b, c){
		this.notesComments.unshift({name: a, dateTime: b, commentText: c});
		alternateComments();
		$('#new-comment').val('');
	},
};

var viewModel;
var emptyViewModel = ko.mapping.fromJS(data);//create the viewModel object from the JavaScript object

//Print the current viewModel object
function getUpdatedViewModel()
{
	console.log(ko.mapping.toJS(viewModel));
}

//Remove and Add bindings on load to each node
function reapplyBindings()
{
	$("*[data-bind]").each(function(){
		$(this).unbind();
		ko.cleanNode($(this));
		ko.applyBindings(viewModel, this);
	});
	
	//Add dropdownGrey() function to all drop down lists on page initialization
	$('select').each(function(i, element){
	  dropdownGrey($(this).attr('id'));//initial run
	  $(this).change(function(){//add onchange function
		dropdownGrey($(this).attr('id'))
	  });
	});
	
	//Make date grey when not filled
	$('input[type="date"]').each(function(i, element){
	  dateGrey($(this).attr('id'));//initial run
	  $(this).change(function(){//add onchange function
		dateGrey($(this).attr('id'))
	  });
	});
	
	antiBen();
	
	alternateComments();
	
}

function alternateComments()
{
	$('.direction-l').each(function(i, element){
		$(this).removeClass('direction-l')
		$(this).addClass('direction-r')
	});
	var numComments = 0;
	try
	{
		numComments = ko.mapping.toJS(viewModel).notesComments.length;
	}
	catch(err)
	{
		//console.log(err);
		numComments = 0;
	}
	
	if(numComments%2 == 0)
	{
		$('.direction-r').filter(':odd').each(function(i, element){
			$(this).removeClass('direction-r')
			$(this).addClass('direction-l')
		});
	}
	else
	{
		$('.direction-r').filter(':even').each(function(i, element){
			$(this).removeClass('direction-r')
			$(this).addClass('direction-l')
		});
	}
}

function saveAsJSON()
{
	console.log(ko.mapping.toJSON(viewModel));
}
function resetViewModel()
{
	return ko.mapping.fromJS(data);
}
function drawToCanvas(id, dataUrl)
{
	var myCanvas = document.getElementById(id);
	var ctx = myCanvas.getContext('2d');
	var img = new Image;
	img.onload = function(){
	  ctx.drawImage(img,0,0); // Or at whatever offset you like
	};
	img.src = dataUrl;
}

function antiBen()
{
	$('input').attr('maxLength', 400);
}